[package]
name = "batata"
version = "0.1.0"
authors = ["Tianyu Liang <124244236@qq.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-macros = "0.2.4"
actix-service = "2.0.3"
actix-utils = "3.0.1"
actix-web = { version = "4.12.1" }
anyhow = "1.0.100"
base64 = "0.22.1"
bcrypt = "0.17.1"
bytes = "1.11.0"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive", "env"] }
config = "0.15.19"
dashmap = "6.1.0"
env_logger = "0.11.8"
futures = "0.3.31"
htmlescape = "0.3.1"
if-addrs = "0.14.0"
jsonwebtoken = "9.3.1"
md5 = "0.8.0"
pin-project-lite = "0.2.16"
prost = "0.14.1"
prost-types = "0.14.1"
regex = "1.11.3"
reqwest = { version = "0.12.26", features = ["json"] }
sea-orm = { version = "1.1.19", features = ["sqlx-mysql", "runtime-tokio"] }
serde = "1.0.228"
serde_json = "1.0.145"
serde_with = "3.16.1"
thiserror = "2.0.17"
time = "0.3.44"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
tonic = "0.14.2"
tonic-prost = "0.14.2"
tower = "0.5.2"
tracing = { version = "0.1.43", features = ["log"] }
tracing-bunyan-formatter = "0.3.10"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["registry", "env-filter"] }
uuid = { version = "1.19.0", features = ["v4", "fast-rng", "macro-diagnostics"] }

# Raft consensus
openraft = { version = "0.9.21", features = ["serde", "storage-v2"] }
rocksdb = "0.24.0"
byteorder = "1.5.0"

[build-dependencies]
tonic-prost-build = "0.14.2"

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.
